language: node_js
node_js:
  - "8"
cache: npm

jobs:
  include:
    - stage: unit test
      script:
        - "npm test"
    - stage: JS doc
      script: 
        - "./node_modules/.bin/jsdoc -d ./jsdoc ./www/**/*.js"

stages:
  - name: lint
  - name: unit test
  - name: JS doc
 